### ISSUE TITLE
Testing with tshy output

### ISSUE THREAD

**Issue by mpodwysocki** [isaacs/tshy#13]
This is perhaps more of a discussion than an issue, but I think design-wise it might be helpful to flesh out.

I'm currently working on the Azure SDK for JavaScript to convert over to tshy for our build process so that we can support both the browser and Node in the same codebase. Currently, our system uses Mocha for Node testing and Karma (yes we know it's deprecated) for Web testing. 

Currently, as part of the tshy build process, it does not include the tests in the dist output, but I was wondering if there was a way for us to compile both the source and the tests so that we can run in environments such as Node, Deno, the browser, etc.  Alternatively, there could be just doing a loader at run time to run the tests, but that doesn't seem as well supported across environments just yet.

What would be an ideal scenario for testing per environment such as Node, Deno, and the browser with the tshy output? @isaacs thoughts?

**Comment by isaacs** [comment]
I've seen some projects just put their tests right in src alongside the code, build the tests into `./dist`, and run them that way. Then in package.json, have `"files": ["dist/**/!(*.test.js)"]` to exclude the tests from the distributed package. That'd be one way to get what you're describing, because from tshy's/tsc's pov, they're just part of the program. Personally, I usually like a bigger/clearer separation between tests and distributed modules, but there's advantages either way.

A design goal of tshy is to be as minimal as possible with its configuration, so the naming of things like `src` and `dist` are intentionally hard-coded. There's no way to tell it to _also_ build `./test` into `./test-build` or something. But what you could do is lean on that convention and just stack it. Ie, write your program in `./src`, and build it into `./dist/{dialect}`, and then treat `./test` as another "package" of sorts. Ie, you'd have `test/package.json` that has a matching `tshy` config section, write tests in TypeScript in `./test/src`, and run tests from `./test/dist/{dialect}`.
