### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by valerii15298** [isaacs/tshy#23]
Why emit folder is called `commonjs` instead of `cjs`? That is very strange. I think the naming should be more consistent either use full names or short ones but not mix them.
`cjs` and `esm` - seems best choice
or `commonjs` and `esmidules` - this one doesn't look very good to be honest

**Comment by isaacs** [comment]
The dialect is `commonjs`. `cjs` is the file extension.

The override for commonjs is `-cjs.cts` instead of `-commonjs.cts` because it was initially the only override, before other dialect support was added. That's unfortunate, imo.

Thanks for the suggestion, I'm probably not going to change it again, though. It's fine.
