### ISSUE TITLE
Issue importing dual package in commonjs build

### ISSUE THREAD

**Issue by svallory** [isaacs/tshy#50]
Hi there!

I'm getting the following error trying to import unjs's `citty`

```
src/bin.ts:3:40 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("citty")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

3 import { defineCommand, runMain } from 'citty';
```

The thing is, according to citty's does [define a `require` export](https://github.com/unjs/citty/blob/main/package.json#L13)

How should I deal with this when using `tshy`? Do I need to define a `-cjt.cts` polyfill to explicitly use `require`?

**Comment by isaacs** [comment]
Most likely your program does not set `module: "node16"` or `module: "nodenext"`, so it isn't respecting the `exports` conditions provided by citty.

**Comment by isaacs** [comment]
But yes, if you want `import` in TS to be compiled into `require()` unambiguously, you will need a cjs polyfill, or use `import { createRequire } from 'node:module'` to create a require() function.

**Comment by svallory** [comment]
> Most likely your program does not set `module: "node16"` or `module: "nodenext"`, so it isn't respecting the `exports` conditions provided by citty.

I'm using the tsconfig generated by `tshy`

> But yes, if you want `import` in TS to be compiled into `require()` unambiguously, you will need a cjs polyfill, or use `import { createRequire } from 'node:module'` to create a require() function.

That may be it then. But that's not actually my requirement. 

So @isaacs will I have to write polyfills for every import when the imported packages exports both esm and cjs?

**Comment by svallory** [comment]
Hey @isaacs can you please take a second look at this?

I think that if there was an issue with my code then running `tsc -p ./.tshy/commonjs.json --module commonjs --moduleResolution node10` after setting `"type": "commonjs"` in my `package.json` should not work, right?

Here's the full script I'm using. It seems like this is kind of what `tshy` should be doing...

```sh
tsc -p ./.tshy/commonjs.json --module commonjs --moduleResolution node10
mv -f .tshy-build/commonjs/package-info-cjs.cjs .tshy-build/commonjs/package-info.js
rm -rf sandbox/test-cjs
node .tshy-build/commonjs/bin.js sandbox/test-cjs
```

That works perfectly, but simply running `tshy` does not.

I pushed a branch here if you want to reproduce it:

https://github.com/svallory/moon-launch/tree/tshy

That script is located at `./scripts/build-and-run-commonjs.sh`

**Comment by isaacs** [comment]
> So @isaacs will I have to write polyfills for every import when the imported packages exports both esm and cjs?

Of course not. Just use `import` in ts, and it'll compile to either require or import, depending on the build type.

I'll take a closer look later today.

**Comment by shellscape** [comment]
@isaacs just ran into this same issue today with the `hash-it` package. `// @ts-ignore` was my only escape hatch.

**Comment by isaacs** [comment]
@shellscape This is a bug in the hash-it module.

It defines `require` and `import` exports, but it does not create a `package.json` file in its `dist/cjs/` folder to override the `"type": "module"` setting in its root package.json file.

Maybe post an issue to hash-it suggesting that they use tshy instead of trying to hand-roll this stuff, since it's damn near impossible for humans to get right, no matter how knowledgeable they are about how it all works?

**Comment by isaacs** [comment]
Though, I guess, since the file extension is `.cjs`, it arguably is a bug in tsc, since Node will interpret it as CommonJS no matter what the package.json says. But, that's why it's having problems, tsc is interpreting it as ESM.

**Comment by shellscape** [comment]
yeah, I agree in general and in principle. I was actually heading to their repo to open an issue about it, when I ran into a half dozen other packages in my project that have the same problem. curiously, it's only an issue when I'm using tshy. before I moved to use tsup I was using TSC straight up and never ran into these issues. I think it may be more nuanced than just a bug with typescript itself. I'm also getting these errors on imports that are only for type imports, and that includes packages like Uno CSS that are absolutely doing things properly

**Comment by isaacs** [comment]
@svallory 

```
tsc -p ./.tshy/commonjs.json --module commonjs --moduleResolution node10
mv -f .tshy-build/commonjs/package-info-cjs.cjs .tshy-build/commonjs/package-info.js
rm -rf sandbox/test-cjs
node .tshy-build/commonjs/bin.js sandbox/test-cjs
```

That is not what tshy is doing. It doesn't set the `module` to `commonjs` or `moduleResolution` to `node10` (both of those options are deprecated). It sets `module` to `nodenext` and `moduleResolution` to `nodenext`.

**Comment by shellscape** [comment]
this is one of those instances I think it's fair for tshy to provide a path forward. would be happy to create a reproduction showing the behavior with a handful of packages. I think that would be miles better than having a lot of ts-igmore directives annotated by a link back to this issue

**Comment by isaacs** [comment]
@shellscape Well, if you want to use ESM-only code in a CommonJS program, you really have no option except to use a dynamic import. There's no way that tshy can make `require('chalk')` work or fix tsc interpreting a module as ESM when it ends in `.cjs`.

@svallory The issue with building your example program for commonjs is that it's importing `chalk`. That is an ESM-only module, you'll have to load it with a dynamic import if you want to build for CommonJS. Or, as you have it in the repo, set `"dialects": ["esm"]`, and just embrace the new paradigm, I guess.

**Comment by isaacs** [comment]
Oh! No, moon-launch isn't importing chalk, that was the wrong repo, my bad.

The issue here is `citty`, which is even more broken, because it's using the same type defs for both ESM and CommonJS, which never ever works. There is no world in which you can build for CommonJS, and load citty without errors, sorry. It's broken, and outside my power to fix.

Suggestion is the same as for hash-it: they should be using tshy instead of trying to do this by hand. It's not possible for humans.

**Comment by shellscape** [comment]
That's not what we're talking about here though. A simple type only import is failing in the same way, and that definitely shouldn't. 

`import type { Foo } from 'esmdevil'` where it doesn't matter if esmdevil has proper dual support or not - it always fails.

I'd think it would be better to be open to seeing a repro before dismissing what you haven't yet put eyes on. I'm fairly confident this is an issue isolated to tshy and the config it's using with tsc.

**Comment by isaacs** [comment]
@svallory No, tshy should not be using deprecated options. The way forward is to use the supported options in the supported version of TypeScript, and rely on node16/nodenext behavior.

@shellscape 

> That's not what we're talking about here though. A simple type only import is failing in the same way, and that definitely shouldn't.
> `import type { Foo } from 'esmdevil'` where it doesn't matter if esmdevil has proper dual support or not - it always fails.

In this case, the module _only_ exports ESM. Yes, they have both `require()` and `import()` exports, but only one *type* expert, and that's being interpreted as ESM, so for TypeScript, it's ESM-only. You cannot import types from ESM only into CommonJS.

It does matter if it does dual exports properly or not, even for type imports. So yes, that definitely should be failing if you are building CJS and the module is (according to TSC) ESM-only. That's never worked properly, the only change is that in recent versions of typescript, it fails fully rather than half-working in a subtly broken state.

> curiously, it's only an issue when I'm using tshy. before I moved to use tsup I was using TSC straight up and never ran into these issues.

Depending on what version of TSC you were using, it might not have raised an error, but it would have been building incorrectly. This was a really big problem that only got ironed out in the last few TypeScript releases, starting with 5.2 or so. If you were using earlier versions of TypeScript, then it would've appeared to work, but shipped incorrect types with your module. That's part of why we're in this mess, actually.

All tshy is doing is shuffling config files around and running `tsc`.

When using tsup or tsx, you don't encounter this problem, because those transpilers _do not do any type checking at all_, they just strip types.

>  I think it may be more nuanced than just a bug with typescript itself. I'm also getting these errors on imports that are only for type imports, and that includes packages like Uno CSS that are absolutely doing things properly

Uno CSS is absolutely not doing things "properly", if by that you mean hybrid exports. `@unocss/core` is ESM-only. See: https://github.com/unocss/unocss/blob/main/packages/core/package.json

Citty is not doing things properly, either. It has require and import endpoints, but it serves the same types for both, so from TS's point of view, it's ESM-only. https://github.com/unjs/citty/blob/main/package.json#L9-L14

Hash-it is _very close_, but since it doesn't put a package.json in the dist folder like tshy does, those files in `dist/cjs/...` still get interpreted by TypeScript as being ESM. But its exports look correct, to my fallible human eyes at least. https://github.com/planttheidea/hash-it/blob/master/package.json#L55-L70

**Comment by svallory** [comment]
> @svallory No, tshy should not be using deprecated options. The way forward is to use the supported options in the supported version of TypeScript, and rely on node16/nodenext behavior.

I clear couldn't get my point across, but that's fine. We are in complete agreement about what you said here :)
