### ISSUE TITLE
enable discussions for dumb questions like this

### ISSUE THREAD

**Issue by boneskull** [isaacs/tshy#51]
I added `selfLink: false` to my `tshy` config because I saw `node_modules` in my `dist` folder and started to worry it'd be published.  But--just now--I realized that `npm` probably would avoid packing that folder unless explicitly instructed to (is that right?).

...but I'm still fuzzy on what `selfLink: false` implies.  What's a _local package export_?  The top search result for this phrase is [this site](https://npm.im/tshy).

**Comment by svallory** [comment]
A _local package export_ is an export from the package you are building. Some people avoid using relative imports by doing `import X from "my_package"` where `my_package` is the package you are building.

Node will look for that export in the `exports` field of your `package.json`, but since `tshy` manages the `exports` 
for you after the build is done, the temporary `package.json` it generates to compile your project will not contain it.

The work around is then to symlink your package to a `node_modules` inside `src` for compilation and inside `dist` to support tests that load code from `dist` instead of `src`

It will not automatically be published as npm will expect that installing your package will re-create the `node_modules` with all the required dependencies. 

At the very end of the readme there's a [Local Package Exports](https://github.com/isaacs/tshy?tab=readme-ov-file#local-package-exports) section with a `tl;dr` with more details if you want to read more.

@isaacs I also found the term "local" confusing at first. Maybe it is better to call it "current package exports" or "Importing package.json exports" ? I don't know 🤷🏻‍♂️

**Comment by isaacs** [comment]
I think technically the tl;dr isn't the bit that's collapsed, the tl;dr is the bit you see, and the longer explanation is the bit that's collapsed.

I've seen them referred to as "local package exports" in discussions, but the node docs calls it "self-referencing a package by its name".
