### ISSUE TITLE
False Positive Errors on Dynamic Imports in CommonJS Build

### ISSUE THREAD

**Issue by shellscape** [isaacs/tshy#60]
Consider a package like `@unocss/core` which only exports ESM, and a `index.ts` file which is built by tshy for commonjs and esm. In that file we're importing a type (in a type-only import) and we're also doing a dynamic import later on in code to accommodate esm and commonjs. 

```ts
// index.ts
import type { ConfigBase } from '@unocss/core';

export const doeet = async () => {
  const { createGenerator } = await import('@unocss/core');
  
  return createGenerator(...);
};
```

The esm build will pass just fine. However, the commonjs build throws the following error:

```
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@unocss/core")' call instead.
```

That error is thrown for both the type-only import as well as the import in the `doeet` body. And that's curious, because _it is_ a dynamic import already in the `doeet` body. Not sure if the type-only import error is a bug in TypeScript but it's damn peculiar. 

The only way I've found around this with tshy is to annotate a poopton of `// @ts-ignore` everywhere.

**Comment by isaacs** [comment]
When building for CommonJS, tsc will only allow top-level import syntax if it can resolve to a CommonJS endpont.

I know, it's type-only, it sort of seems like it ought to be allowed. But there are no CommonJS types, so the correct type of `require('@unocss/core')` is "nope, not found, doesn't exist".

If you want TS to provide a way to pull types from an ESM-only package into a CommonJS program, that's a feature request for typescript, not tshy, sorry.

**Comment by isaacs** [comment]
I tried messing with `type C = typeof import('@unocss/core')` but that also fails. No way to get at those types without writing ESM only, I'm afraid.

**Comment by shellscape** [comment]
And yet, it compiles fine and without error with tsc if the afore mentioned deprecated module and resolution are used.

I don't think this is a sorry-about-your-luck situation. After spending so much time as maintainer in the bundler project landscape,I recognize that there are edge and corner cases with are worthy of being accommodated. Sad that you're not open to a path forward here, so this will probably require a fork that makes those accomodations.

**Comment by isaacs** [comment]
@shellscape Please do fork tshy and make whatever changes to it that you'd like! Don't say that as if it's a sad thing, it's actually the point, and what you _should_ be doing. That's why I chose the license I did, and made it open source, so that people could modify it to suit their purposes. Seeing that happen is one of the great joys of my life <3

> And yet, it compiles fine and without error with tsc if the afore mentioned deprecated module and resolution are used.

Microsoft almost never drops support for anything. My guess is that it will probably keep working exactly as it did, forever. But, there is a good chance that your exported types will be incorrect if you use those options (that's why they're not recommended).

_I'm_ not willing to support everything that TSC has ever supported though. Tshy is a tool that is designed to create a very particular kind of extremely correct hybrid project, with accurate types in all environments.

Sometimes you have to use code that incorrectly advertises its types and/or its code, or that only exports as ESM or only as CommonJS. We can't boil oceans. But for my own preference, I'd rather not pretend it is all good; instead, I'd rather make the affordances necessary _in my code_ (ie, the poopton of `//@ts-ignore` or `as { whatever }` overrides, writing my own local `module.d.ts`, whatever), but make sure that what I actually export is correct.

If you have a different preference, and would prefer to pass the incorrect types onto your users, then that's certainly a choice you can make. But it's not a choice that is going to be codified in tshy's behavior, because tshy is my project, so it is the result of my choices, not anyone else's.

So no, it's not a "sorry, you're out of luck" situation, not at all! It's a "Hooray, you're in luck! You get your own custom tool, hand crafted to your unique preferences, and even better, it's mostly already done by someone else!" I'd love to hear how it goes.
