### ISSUE TITLE
[Question] Best Practices for supporting .tshy directory

### ISSUE THREAD

**Issue by mpodwysocki** [isaacs/tshy#78]
I know this may be a simple question, but, is there a best practice as to whether to check in the `.tshy` directory or have it as part of the `.gitignore` file and ignored as per maintaining a repository?

**Comment by isaacs** [comment]
Personally, I check in `.tshy`, because I use the `.tshy/esm.json` as the project when building docs, so it's just more convenient if my typedoc script already has the tsconfig it needs. Also it's nice to notice when tshy changes what it's doing. It's deterministic and not based on the machine environment in any way, so safe to check in.

But you can definitely ignore it. Tshy will always create it if it's missing or different.

So really it's a matter of taste, I guess. No strong reason to do one or the other.

**Comment by isaacs** [comment]
If you're using incremental builds, though, definitely ignore `.tshy-build`, because that'll have a bunch of tsc artifacts in it.
